spring:
  application:
    name: ServiceHub
  datasource:
    url: jdbc:mysql://localhost:3306/servicehub?createDatabaseIfNotExist=true
    username: root
    password: bikram123@

  jpa:
    show-sql: true

