spring:
  application:
    name: QuestX
  datasource:
    url: jdbc:mysql://localhost:3306/servicehub?createDatabaseIfNotExist=true
    username: root
    password: bikram123@

  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 #15min
    refreshTokenExpiration: 604800 #7days

  mail:
    host: smtp.gmail.com
    port: 587
    username: questx.bca@gmail.com
    password: zwytmrpzuakvridm
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

  data:
    redis:
      host: localhost
      port: 6379

esewa:
  merchantId: EPAYTEST
  secretKey: "8gBm/:&EnhH.1/q"
  successUrl: "http://localhost:8080/payments/esewa/success"
  failureUrl: "http://localhost:8080/payments/esewa/failure"
  paymentUrl: "https://uat.esewa.com.np/epay/main:"
  verificationUrl: "https://uat.esewa.com.np/epay/transrec"