spring:
  application:
    name: QuestX
  datasource:
    url: jdbc:mysql://localhost:3306/servicehub?createDatabaseIfNotExist=true
    username: root
    password: bikram123@

  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 #15min
    refreshTokenExpiration: 604800 #7days

  mail:
    host: smtp.gmail.com
    port: 587
    username: questx.bca@gmail.com
    password: zwytmrpzuakvridm
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

  data:
    redis:
      host: localhost
      port: 6379


google:
  api:
    key: ${GOOGLE_MAPS_API_KEY}